version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - checkout

      - run:
          name: Build Python
          command: |
            chmod u+x ./build-python.sh
            ./build-python.sh

      - store_artifacts:
          path: /artifact
