version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: arm.large
    steps:
      - checkout

      - run:
          name: Build Python
          command: |
            chmod u+x install-pyton.sh
            ./install-pyton.sh

      - store_artifacts:
          path: /artifact
