version: 2.1
jobs:
  build:
    docker:
      - image: arm64v8/debian:bullseye
    steps:
      - checkout

      - run:
          name: Build Python
          command: |
            chmod u+x install-pyton.sh
            ./install-pyton.sh

      - store_artifacts:
          path: /artifact
